In [16]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, neighbors
from sklearn.model_selection import cross_validate, train_test_split

In [2]:
df = pd.read_csv('breast-cancer-wisconsin.data')

In [3]:
df.head()

id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0  1000025                5               1                1              1   
1  1002945                5               4                4              5   
2  1015425                3               1                1              1   
3  1016277                6               8                8              1   
4  1017023                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

In [4]:
df.tail()

id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
694  776715                3               1                1              1   
695  841769                2               1                1              1   
696  888820                5              10               10              3   
697  897471                4               8                6              4   
698  897471                4               8                8              5   

     single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
694                       3           2            1              1        1   
695                       2           1            1              1        1   
696                       7           3            8             10        2   
697                       3           4           10              6        1   
698                       4           5           10              4        1   

     class  
694      2  
695      2  
696      4  
697      4  
698      4

In [5]:
# After reading the file we found we have missing data represented by '?', we will replace it with -99999

In [7]:
df.replace('?', -99999, inplace=True)

In [8]:
# Id column is of no use so we will drop it

In [9]:
df.drop(['id'], axis=1, inplace=True)

In [10]:
df.head()

clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0                5               1                1              1   
1                5               4                4              5   
2                3               1                1              1   
3                6               8                8              1   
4                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

In [11]:
# Creating the features and labels 

In [13]:
X = np.array(df.drop(['class'], axis=1))
y = np.array(df['class'])

In [14]:
X

array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [17]:
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [18]:
# Separating data 

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)   

In [21]:
# STEPS:
# Define Classifier
# fit the data
# Calculate Score or accuracy

In [22]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [23]:
accuracy = clf.score(X_test, y_test)

In [24]:
accuracy

0.95

In [25]:
# Making Predictions
# Make an Example measures data
# Use classifier predict

In [36]:
example_measures = np.array([4,2,1,1,1,2,3,2,1])
example_measures = example_measures.reshape(1,-1)
example_measures.shape

(1, 9)

In [37]:
prediction = clf.predict(example_measures)


In [38]:
print(prediction)

[2]


In [45]:
example_measures = np.array([[4,2,1,1,1,2,3,2,1], [4,2,1,2,3,2,3,2,1]])

In [46]:
example_measures.reshape(2,-1)

array([[4, 2, 1, 1, 1, 2, 3, 2, 1],
       [4, 2, 1, 2, 3, 2, 3, 2, 1]])

In [47]:
prediction = clf.predict(example_measures)
print(prediction)

[2 2]


In [ ]:
# More general is to replace the number with len(example_measures)

In [50]:
example_measures.reshape(len(example_measures),-1)

array([[4, 2, 1, 1, 1, 2, 3, 2, 1],
       [4, 2, 1, 2, 3, 2, 3, 2, 1]])

In [51]:
prediction = clf.predict(example_measures)
print(prediction)

[2 2]
